# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: nix flake check
"on": push
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - uses: cachix/cachix-action@v15
        with:
          name: nxvm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check
